### ISSUE TITLE
error: Uncaught (in promise) Error: Request to v1/page/… failed

### ISSUE THREAD

**Issue by lens0021** [saschanaz/femiwiki-prsk-music-list#5]
6월 30일경부터 액션 실패 중
```
Task wiki deno run --allow-read --allow-env --allow-write --allow-net wiki.js
error: Uncaught (in promise) Error: Request to v1/page/%ED%8B%80%3A%ED%94%84%EB%A1%9C%EC%84%B8%EC%B9%B4%20%EC%95%85%EA%B3%A1%20%EB%AA%A9%EB%A1%9D failed
      throw new Error(`Request to ${endpoint} failed`, { cause: data });
            ^
    at WikiActionClient.request (file:///home/runner/work/femiwiki-prsk-music-list/femiwiki-prsk-music-list/lib/wikiapi.js:32:13)
    at eventLoopTick (ext:core/01_core.js:168:[7](https://github.com/saschanaz/femiwiki-prsk-music-list/actions/runs/10337916744/job/28615331152#step:7:8))
    at async WikiActionClient.edit (file:///home/runner/work/femiwiki-prsk-music-list/femiwiki-prsk-music-list/lib/wikiapi.js:48:12)
    at async file:///home/runner/work/femiwiki-prsk-music-list/femiwiki-prsk-music-list/wiki.js:24:22
Caused by: {
  message: "Error: exception of type Error",
  httpCode: 500,
  httpReason: "Internal Server Error"
}
Error: Process completed with exit code 1.
```

당시 페미위키는 미디어위키 1.41에서 1.42.1[^1]로 업그레이드했습니다.

[^1]: https://www.mediawiki.org/wiki/Release_notes/1.42

**Comment by saschanaz** [comment]
HTTP 500이 뜨는 건 미디어위키 버그 같은데 API 변경사항이 있어서 발생한 건지 그냥 버그인지 자세한 정보가 없어서 곤란하네요 🤔
